# Generated by Django 4.0.4 on 2022-04-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='origin',
            new_name='title',
        ),
    ]
